### ISSUE TITLE
Descending order stream support

### ISSUE THREAD

**Issue by yongman** [danieldg/ordered-stream#3]
I want to know doest this support descending order stream, I found the doc in source code https://github.com/danieldg/ordered-stream/blob/master/src/lib.rs#L69, it says stream values must be ascending order.

But how can I make it to support descending order streams merge?

**Comment by danieldg** [comment]
One simple way is to just use `std::cmp::Reverse` on the ordering element.

**Comment by yongman** [comment]
@danieldg The stream data may be too large and can not reverse in memory, the goal that I use stream is fetching data in lazy way.

**Comment by danieldg** [comment]
Yes, that's what `std::cmp::Reverse` lets you do.

**Comment by yongman** [comment]
@danieldg the stream fetch data in an upstream which will stream data in descending order, how can `Reverse` make it to ascending without fetching all data first?

**Comment by yongman** [comment]
@danieldg Oh, I see what you means, thanks.
